"""initial_schema

Revision ID: 0685323be60f
Revises: 
Create Date: 2018-08-30 17:42:18.780407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0685323be60f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summoners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profileiconid', sa.Integer(), nullable=True),
    sa.Column('revisiondate', sa.Integer(), nullable=True),
    sa.Column('summonerlevel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accountid')
    )
    op.create_index(op.f('ix_summoners_name'), 'summoners', ['name'], unique=False)
    op.create_table('user_leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summonerid', sa.Integer(), nullable=True),
    sa.Column('queuetype', sa.String(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('leaguepoints', sa.Integer(), nullable=True),
    sa.Column('hotstreak', sa.Boolean(), nullable=True),
    sa.Column('veteran', sa.Boolean(), nullable=True),
    sa.Column('playerorteamid', sa.Integer(), nullable=True),
    sa.Column('leaguename', sa.String(), nullable=True),
    sa.Column('playerorteamname', sa.String(), nullable=True),
    sa.Column('inactive', sa.Boolean(), nullable=True),
    sa.Column('freshblood', sa.Boolean(), nullable=True),
    sa.Column('leagueid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['summonerid'], ['summoners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_leagues_summonerid'), 'user_leagues', ['summonerid'], unique=False)
    op.create_table('user_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountid', sa.Integer(), nullable=True),
    sa.Column('lane', sa.String(), nullable=True),
    sa.Column('gameid', sa.Integer(), nullable=True),
    sa.Column('champion', sa.Integer(), nullable=True),
    sa.Column('platformid', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('queue', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accountid'], ['summoners.accountid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_matches_accountid'), 'user_matches', ['accountid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_matches_accountid'), table_name='user_matches')
    op.drop_table('user_matches')
    op.drop_index(op.f('ix_user_leagues_summonerid'), table_name='user_leagues')
    op.drop_table('user_leagues')
    op.drop_index(op.f('ix_summoners_name'), table_name='summoners')
    op.drop_table('summoners')
    # ### end Alembic commands ###
