"""summoners table

Revision ID: 1b4fbccc34e7
Revises: 
Create Date: 2018-08-24 06:26:19.051233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4fbccc34e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summoners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profileiconid', sa.Integer(), nullable=True),
    sa.Column('revisiondate', sa.Integer(), nullable=True),
    sa.Column('summonerlevel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'accountid')
    )
    op.create_table('user_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountid', sa.Integer(), nullable=True),
    sa.Column('lane', sa.String(), nullable=True),
    sa.Column('gameid', sa.Integer(), nullable=True),
    sa.Column('champion', sa.Integer(), nullable=True),
    sa.Column('platformid', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('queue', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accountid'], ['summoners.accountid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_matches')
    op.drop_table('summoners')
    # ### end Alembic commands ###
